config/routes.rb
Rails.application.routes.draw do
  root 'formulas#index'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  resources :formulas

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  has_one :formula
end

app/models/formula.rb
class Formula < ApplicationRecord
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :directions, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>" }, dependent: :destroy

  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :directions

  validates_presence_of :title, :description
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_one :formula
end

app/models/user.rb
class User < ApplicationRecord
  has_many :formulas

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new]

  def index
    @formulas = Formula.all.order('created_at DESC')
  end

  def show
  end

  def new
    @formula = current_user.formulas.build
  end

  def create
    @formula = current_user.formulas.build(formula_params)
    if @formula.save!
      redirect_to @formula, notice: 'Recipe added!'
    else
      render :new
      flash.now.alert = 'Invalid entry'
    end
  end

  private

  def find_recipe
    @formula = Formula.find(params[:id])
  end

  def require_login
    unless current_user
      redirect_to root_path, notice: 'You must be logged in.'
    end
  end

  def formula_params
    params.require(:formula).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_username(params[:session][:username])
     if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to root_path, notice: 'Logged in!'
     else
       flash.now.alert = 'Invalid email or password'
       render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/formulas/_direction_fields.html.erb
<div class="columns">
  <div class="column is-half">
    <h2>Directions</h2>
    <%= f.input_field :step, class: 'input is-large', placeholder: 'Direction' %>
    <%= link_to_remove_association 'Remove', f %>
  </div>
</div>

app/views/formulas/_ingredient_fields.html.erb
<div class="columns">
  <div class="column is-half">
    <h2>Ingredients</h2>
    <%= f.input_field :name, class: 'input is-large', placeholder: 'Ingredient' %>
    <%= link_to_remove_association 'Remove', f %>
  </div>
</div>

app/views/formulas/index.html.erb
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="columns is-multiline is-mobile" style="margin-top: 2.5%;">
        <% @formulas.each do |formula| %>
          <div class="column is-one-third">
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by4">
                  <%= link_to formula_path(formula) do %>
                    <%= image_tag formula.image.url(:medium), style: 'width: 300px; height: 300px' %>
                  <% end %>
                </figure>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-32x32">
                      <%= link_to formula_path(formula) do %>
                        <%= image_tag formula.image.url(:medium) %>
                      <% end %>
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-5"><%= formula.title %></p>
                  </div>
                </div>

                <div class="content">
                  <p><%= formula.description %></p>
                  <br>
                  <small><%= formula.created_at.strftime('%B %d %Y') %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/formulas/new.html.erb
<div class="form-wrapper">
  <%= render 'partials/formula_form' %>
</div>

app/views/formulas/show.html.erb
<div class="container" style="margin-top: 5%;">
  <div class="columns">
    <div class="column" style="margin-bottom: 2.5%">
      <article class="media" style="align-items: center;">
        <figure class="media-left">
          <p class="image">
            <%= image_tag @formula.image.url(:medium) %>
          </p>
        </figure>
        <div class="media-content" style="margin-left: 5%; background-color: rgba(0, 0, 0, 0.1);">
          <div class="content" style="padding: 2.5%">
            <p>
              <strong><%= @formula.user.username %></strong>
              <br>
              <h1><%= @formula.title %></h1>
              <p><%= @formula.description %></p>
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>

  <div class="columns">
    <div class="column is-half">
      <h1 class="title">Ingredients</h1>
      <% @count = 0 %>
      <% @formula.ingredients.each_with_index do |ingredient| %>
        <p><%= @count += 1 %>. <%= ingredient.name %></p>
      <% end %>
    </div>
    <div class="column is-half">
      <h1 class="title">Directions</h1>
      <% @count = 0 %>
      <% @formula.directions.each do |direction| %>
        <p><%= @count += 1 %>. <%= direction.step %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.2.3/css/bulma.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav has-shadow">
      <div class="nav-left">
        <h1 class="title is-2"><%= link_to 'Recipes', root_path %></h1>
      </div>

      <div class="nav-center">
        <a class="nav-item" href="#">
          <span class="icon">
            <i class="fa fa-github"></i>
          </span>
        </a>
        <a class="nav-item" href="#">
          <span class="icon">
            <i class="fa fa-twitter"></i>
          </span>
        </a>
      </div>

      <!-- <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span> -->

      <div class="nav-right nav-menu">
        <%= link_to 'Home', root_path, class: 'nav-item' %>
        <%= link_to 'New Recipe', new_formula_path, class: 'nav-item' %>
      </div>
    </nav>
    <% if flash[:notice] || flash[:alert] %>
      <div class="notification">
        <p><%= flash[:notice] %></p>
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_formula_form.html.erb
<div class="container" style="margin-top: 5%">
  <%= simple_form_for @formula, {multipart: true} do |f| %>
    <div class="columns">
      <div class="column is-half">
        <p class="control"><%= f.input_field :title, class: 'input is-large', placeholder: 'Recipe' %></p>
        <p class="control"><%= f.input_field :description, class: 'textarea', placeholder: 'Details' %></p>
        <p class="control"><%= f.input_field :image %></p>
        <%= f.submit 'Add recipe', class: 'button is-large' %>
      </div>
    </div>

    <div class="columns">
      <div class="column is-half">
        <div class="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients %>
          </div>
          
        </div>
      </div>
      <div class="column is-half">
        <div class="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Direction', f, :directions %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_login.html.erb
<h1>Log in</h1>
<%= simple_form_for :session, url: sessions_path do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.submit :submit %>
<% end %>